<?php

namespace Database\Seeders;

use App\Models\Neighborhood;
use App\Models\SubDistrict;
use Illuminate\Database\Seeder;

class NeighborhoodSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['sub_district_name' => 'Balaraja', 'postal_code' => '15610'],
            ['sub_district_name' => 'Cangkudu', 'postal_code' => '15610'],
            ['sub_district_name' => 'Talagasari', 'postal_code' => '15610'],
            ['sub_district_name' => 'Tobat', 'postal_code' => '15610'],
            ['sub_district_name' => 'Sentul', 'postal_code' => '15610'],
            ['sub_district_name' => 'Gembong', 'postal_code' => '15610'],
            ['sub_district_name' => 'Sukamurni (Suka Murni)', 'postal_code' => '15610'],
            ['sub_district_name' => 'Saga', 'postal_code' => '15610'],
            ['sub_district_name' => 'Sentul Jaya', 'postal_code' => '15610'],
            ['sub_district_name' => 'Pangkat', 'postal_code' => '15611'],
            ['sub_district_name' => 'Pabuaran', 'postal_code' => '15611'],
            ['sub_district_name' => 'Pasir Muncang', 'postal_code' => '15611'],
            ['sub_district_name' => 'Sumur Bandung', 'postal_code' => '15611'],
            ['sub_district_name' => 'Jayanti', 'postal_code' => '15611'],
            ['sub_district_name' => 'Dangdeur (Dang Deur)', 'postal_code' => '15611'],
            ['sub_district_name' => 'Cikande', 'postal_code' => '15611'],
            ['sub_district_name' => 'Pasir Gintung', 'postal_code' => '15611'],
            ['sub_district_name' => 'Tigaraksa', 'postal_code' => '15721'],
            ['sub_district_name' => 'Kadu Agung', 'postal_code' => '15721'],
            ['sub_district_name' => 'Pasir Bolang', 'postal_code' => '15721'],
            ['sub_district_name' => 'Matagara (Mata Gara)', 'postal_code' => '15721'],
            ['sub_district_name' => 'Pasir Nangka', 'postal_code' => '15721'],
            ['sub_district_name' => 'Pete', 'postal_code' => '15721'],
            ['sub_district_name' => 'Tegalsari', 'postal_code' => '15721'],
            ['sub_district_name' => 'Pematang', 'postal_code' => '15721'],
            ['sub_district_name' => 'Cisereh', 'postal_code' => '15721'],
            ['sub_district_name' => 'Margasari (Marga Sari)', 'postal_code' => '15721'],
            ['sub_district_name' => 'Cileles', 'postal_code' => '15721'],
            ['sub_district_name' => 'Sodong', 'postal_code' => '15721'],
            ['sub_district_name' => 'Tapos', 'postal_code' => '15721'],
            ['sub_district_name' => 'Bantar Panjang', 'postal_code' => '15721'],
            ['sub_district_name' => 'Sukamanah (Suka Manah)', 'postal_code' => '15720'],
            ['sub_district_name' => 'Jambe', 'postal_code' => '15720'],
            ['sub_district_name' => 'Tipar Raya (Tipar Jaya / Tiparraya)', 'postal_code' => '15720'],
            ['sub_district_name' => 'Taban', 'postal_code' => '15720'],
            ['sub_district_name' => 'Daru', 'postal_code' => '15720'],
            ['sub_district_name' => 'Kutruk', 'postal_code' => '15720'],
            ['sub_district_name' => 'Ranca Buaya (Rancabuaya)', 'postal_code' => '15720'],
            ['sub_district_name' => 'Mekarsari', 'postal_code' => '15720'],
            ['sub_district_name' => 'Ancol Pasir', 'postal_code' => '15720'],
            ['sub_district_name' => 'Pasir Barat', 'postal_code' => '15720'],
            ['sub_district_name' => 'Cisoka', 'postal_code' => '15730'],
            ['sub_district_name' => 'Caringin', 'postal_code' => '15730'],
            ['sub_district_name' => 'Selapajang', 'postal_code' => '15730'],
            ['sub_district_name' => 'Sukatani', 'postal_code' => '15730'],
            ['sub_district_name' => 'Bojong Loa (Bojongloa)', 'postal_code' => '15730'],
            ['sub_district_name' => 'Cibugel', 'postal_code' => '15730'],
            ['sub_district_name' => 'Cempaka', 'postal_code' => '15730'],
            ['sub_district_name' => 'Carenang', 'postal_code' => '15730'],
            ['sub_district_name' => 'Karang Harja (Karangharja)', 'postal_code' => '15730'],
            ['sub_district_name' => 'Jeungjing (Jeung Jing)', 'postal_code' => '15730'],
            ['sub_district_name' => 'Pasir Ampo', 'postal_code' => '15621'],
            ['sub_district_name' => 'Rancailat (Ranca Ilat)', 'postal_code' => '15621'],
            ['sub_district_name' => 'Kemuning', 'postal_code' => '15621'],
            ['sub_district_name' => 'Renged', 'postal_code' => '15621'],
            ['sub_district_name' => 'Talok', 'postal_code' => '15621'],
            ['sub_district_name' => 'Koper', 'postal_code' => '15621'],
            ['sub_district_name' => 'Jengkol', 'postal_code' => '15621'],
            ['sub_district_name' => 'Patrasana (Patra Sana)', 'postal_code' => '15621'],
            ['sub_district_name' => 'Kresek', 'postal_code' => '15621'],
            ['sub_district_name' => 'Kronjo', 'postal_code' => '15550'],
            ['sub_district_name' => 'Pagenjahan', 'postal_code' => '15550'],
            ['sub_district_name' => 'Pasir', 'postal_code' => '15550'],
            ['sub_district_name' => 'Muncung', 'postal_code' => '15550'],
            ['sub_district_name' => 'Pagedangan Ilir', 'postal_code' => '15550'],
            ['sub_district_name' => 'Pagedangan Udik', 'postal_code' => '15550'],
            ['sub_district_name' => 'Pasilian', 'postal_code' => '15550'],
            ['sub_district_name' => 'Bakung', 'postal_code' => '15550'],
            ['sub_district_name' => 'Blukbuk', 'postal_code' => '15550'],
            ['sub_district_name' => 'Cirumpak', 'postal_code' => '15550'],
            ['sub_district_name' => 'Mauk Timur', 'postal_code' => '15531'],
            ['sub_district_name' => 'Mauk Barat', 'postal_code' => '15531'],
            ['sub_district_name' => 'Tegal Kunir Kidul', 'postal_code' => '15531'],
            ['sub_district_name' => 'Tegal Kunir Lor', 'postal_code' => '15531'],
            ['sub_district_name' => 'Sasak', 'postal_code' => '15531'],
            ['sub_district_name' => 'Gunung Sari', 'postal_code' => '15531'],
            ['sub_district_name' => 'Kedung Dalem', 'postal_code' => '15531'],
            ['sub_district_name' => 'Marga Mulya', 'postal_code' => '15531'],
            ['sub_district_name' => 'Tanjung Anom', 'postal_code' => '15531'],
            ['sub_district_name' => 'Jatiwaringin (Jati Waringin)', 'postal_code' => '15531'],
            ['sub_district_name' => 'Banyu Asih', 'postal_code' => '15531'],
            ['sub_district_name' => 'Ketapang', 'postal_code' => '15531'],
            ['sub_district_name' => 'Patramanggala (Patra Manggala)', 'postal_code' => '15530'],
            ['sub_district_name' => 'Karang Anyar', 'postal_code' => '15530'],
            ['sub_district_name' => 'Lontar', 'postal_code' => '15530'],
            ['sub_district_name' => 'Kemiri', 'postal_code' => '15530'],
            ['sub_district_name' => 'Ranca Labuh', 'postal_code' => '15530'],
            ['sub_district_name' => 'Klebet (Kjlebet / Kelebet)', 'postal_code' => '15530'],
            ['sub_district_name' => 'Legok Suka Maju (Legok Sula Maju)', 'postal_code' => '15530'],
            ['sub_district_name' => 'Sukadiri', 'postal_code' => '15532'],
            ['sub_district_name' => 'Buaran Jati', 'postal_code' => '15532'],
            ['sub_district_name' => 'Rawa Kidang', 'postal_code' => '15532'],
            ['sub_district_name' => 'Pekayon', 'postal_code' => '15532'],
            ['sub_district_name' => 'Karang Serang', 'postal_code' => '15532'],
            ['sub_district_name' => 'Kosambi', 'postal_code' => '15532'],
            ['sub_district_name' => 'Mekar Kondang', 'postal_code' => '15532'],
            ['sub_district_name' => 'Gintung', 'postal_code' => '15532'],
            ['sub_district_name' => 'Sukatani (Suka Tani)', 'postal_code' => '15540'],
            ['sub_district_name' => 'Rajeg', 'postal_code' => '15540'],
            ['sub_district_name' => 'Rajeg Mulya (Rajegmulya)', 'postal_code' => '15540'],
            ['sub_district_name' => 'Pangarengan', 'postal_code' => '15540'],
            ['sub_district_name' => 'Jambu Karya', 'postal_code' => '15540'],
            ['sub_district_name' => 'Lembangsari (Lembang Sari)', 'postal_code' => '15540'],
            ['sub_district_name' => 'Sukamanah (Suka Manah)', 'postal_code' => '15540'],
            ['sub_district_name' => 'Tanjakan', 'postal_code' => '15540'],
            ['sub_district_name' => 'Tanjakan Mekar', 'postal_code' => '15540'],
            ['sub_district_name' => 'Sukasari (Suka Sari)', 'postal_code' => '15540'],
            ['sub_district_name' => 'Ranca Bango', 'postal_code' => '15540'],
            ['sub_district_name' => 'Daon', 'postal_code' => '15540'],
            ['sub_district_name' => 'Mekarsari', 'postal_code' => '15540'],
            ['sub_district_name' => 'Sindangsari (Sindang Sari)', 'postal_code' => '15560'],
            ['sub_district_name' => 'Kutabumi (Kuta Bumi)', 'postal_code' => '15560'],
            ['sub_district_name' => 'Kuta Jaya', 'postal_code' => '15560'],
            ['sub_district_name' => 'Kuta Baru', 'postal_code' => '15560'],
            ['sub_district_name' => 'Pasar Kemis', 'postal_code' => '15560'],
            ['sub_district_name' => 'Sukamantri', 'postal_code' => '15560'],
            ['sub_district_name' => 'Pangadegan', 'postal_code' => '15560'],
            ['sub_district_name' => 'Gelam Jaya', 'postal_code' => '15560'],
            ['sub_district_name' => 'Suka Asih (Sukaasih)', 'postal_code' => '15560'],
            ['sub_district_name' => 'Teluknaga (Teluk Naga)', 'postal_code' => '15510'],
            ['sub_district_name' => 'Bojong Renged', 'postal_code' => '15510'],
            ['sub_district_name' => 'Babakan Asem', 'postal_code' => '15510'],
            ['sub_district_name' => 'Keboncau (Kebon Cau)', 'postal_code' => '15510'],
            ['sub_district_name' => 'Pangkalan', 'postal_code' => '15510'],
            ['sub_district_name' => 'Kampung Melayu Timur', 'postal_code' => '15510'],
            ['sub_district_name' => 'Kampung Melayu Barat', 'postal_code' => '15510'],
            ['sub_district_name' => 'Muara', 'postal_code' => '15510'],
            ['sub_district_name' => 'Lemo', 'postal_code' => '15510'],
            ['sub_district_name' => 'Tanjung Pasir', 'postal_code' => '15510'],
            ['sub_district_name' => 'Tegal Angus', 'postal_code' => '15510'],
            ['sub_district_name' => 'Tanjung Burung', 'postal_code' => '15510'],
            ['sub_district_name' => 'Kampung Besar', 'postal_code' => '15510'],
            ['sub_district_name' => 'Kosambi Barat', 'postal_code' => '15213'],
            ['sub_district_name' => 'Salembaran Jaya (Salembaran Raya)', 'postal_code' => '15214'],
            ['sub_district_name' => 'Dadap', 'postal_code' => '15211'],
            ['sub_district_name' => 'Kosambi Timur', 'postal_code' => '15213'],
            ['sub_district_name' => 'Salembaran Jati', 'postal_code' => '15214'],
            ['sub_district_name' => 'Ranga Rengas (Rawa Rengas)', 'postal_code' => '15215'],
            ['sub_district_name' => 'Rawa Burung', 'postal_code' => '15215'],
            ['sub_district_name' => 'Cengklong', 'postal_code' => '15212'],
            ['sub_district_name' => 'Belimbing', 'postal_code' => '15212'],
            ['sub_district_name' => 'Jati Mulya (Jatimulya)', 'postal_code' => '15211'],
            ['sub_district_name' => 'Pakuhaji', 'postal_code' => '15570'],
            ['sub_district_name' => 'Paku Alam', 'postal_code' => '15570'],
            ['sub_district_name' => 'Bunisari (Bonasari)', 'postal_code' => '15570'],
            ['sub_district_name' => 'Rawa Boni', 'postal_code' => '15570'],
            ['sub_district_name' => 'Buaran Mangga', 'postal_code' => '15570'],
            ['sub_district_name' => 'Buaran Bambu', 'postal_code' => '15570'],
            ['sub_district_name' => 'Kalibaru', 'postal_code' => '15570'],
            ['sub_district_name' => 'Kohod', 'postal_code' => '15570'],
            ['sub_district_name' => 'Kramat', 'postal_code' => '15570'],
            ['sub_district_name' => 'Sukawali', 'postal_code' => '15570'],
            ['sub_district_name' => 'Surya Bahari', 'postal_code' => '15570'],
            ['sub_district_name' => 'Kiara Payung', 'postal_code' => '15570'],
            ['sub_district_name' => 'Laksana', 'postal_code' => '15570'],
            ['sub_district_name' => 'Gaga', 'postal_code' => '15570'],
            ['sub_district_name' => 'Sepatan', 'postal_code' => '15520'],
            ['sub_district_name' => 'Karet', 'postal_code' => '15520'],
            ['sub_district_name' => 'Kayu Agung', 'postal_code' => '15520'],
            ['sub_district_name' => 'Kayu Bongkok', 'postal_code' => '15520'],
            ['sub_district_name' => 'Pondok Jaya', 'postal_code' => '15520'],
            ['sub_district_name' => 'Pisangan Jaya', 'postal_code' => '15520'],
            ['sub_district_name' => 'Mekar Jaya', 'postal_code' => '15520'],
            ['sub_district_name' => 'Sarakan', 'postal_code' => '15520'],
            ['sub_district_name' => 'Curug Kulon', 'postal_code' => '15810'],
            ['sub_district_name' => 'Sukabakti (Suka Bakti)', 'postal_code' => '15810'],
            ['sub_district_name' => 'Binong', 'postal_code' => '15810'],
            ['sub_district_name' => 'Curug Wetan', 'postal_code' => '15810'],
            ['sub_district_name' => 'Kadu', 'postal_code' => '15810'],
            ['sub_district_name' => 'Kadu Jaya', 'postal_code' => '15810'],
            ['sub_district_name' => 'Cukanggalih (Cukang Galih)', 'postal_code' => '15810'],
            ['sub_district_name' => 'Sukamulya (Suka Mulya)', 'postal_code' => '15710'],
            ['sub_district_name' => 'Bunder', 'postal_code' => '15710'],
            ['sub_district_name' => 'Cibadak', 'postal_code' => '15710'],
            ['sub_district_name' => 'Talaga', 'postal_code' => '15710'],
            ['sub_district_name' => 'Talagasari (Talaga Sari)', 'postal_code' => '15710'],
            ['sub_district_name' => 'Dukuh', 'postal_code' => '15710'],
            ['sub_district_name' => 'Cikupa', 'postal_code' => '15710'],
            ['sub_district_name' => 'Sukanagara (Suka Nagara)', 'postal_code' => '15710'],
            ['sub_district_name' => 'Bitung Jaya', 'postal_code' => '15710'],
            ['sub_district_name' => 'Pasir Gadung', 'postal_code' => '15710'],
            ['sub_district_name' => 'Sukadamai (Suka Damai)', 'postal_code' => '15710'],
            ['sub_district_name' => 'Pasir Jaya', 'postal_code' => '15710'],
            ['sub_district_name' => 'Budi Mulya', 'postal_code' => '15710'],
            ['sub_district_name' => 'Bojong', 'postal_code' => '15710'],
            ['sub_district_name' => 'Mekar Bakti', 'postal_code' => '15711'],
            ['sub_district_name' => 'Ranca Iyuh', 'postal_code' => '15711'],
            ['sub_district_name' => 'Peusar', 'postal_code' => '15711'],
            ['sub_district_name' => 'Ranca Kalapa', 'postal_code' => '15711'],
            ['sub_district_name' => 'Serdang Kulon', 'postal_code' => '15711'],
            ['sub_district_name' => 'Mekar Jaya', 'postal_code' => '15711'],
            ['sub_district_name' => 'Ciakar', 'postal_code' => '15711'],
            ['sub_district_name' => 'Panongan', 'postal_code' => '15711'],
            ['sub_district_name' => 'Babakan', 'postal_code' => '15820'],
            ['sub_district_name' => 'Caringin', 'postal_code' => '15820'],
            ['sub_district_name' => 'Serdang Wetan', 'postal_code' => '15820'],
            ['sub_district_name' => 'Babat', 'postal_code' => '15820'],
            ['sub_district_name' => 'Ciangir', 'postal_code' => '15820'],
            ['sub_district_name' => 'Legok', 'postal_code' => '15820'],
            ['sub_district_name' => 'Palasari (Pala Sari)', 'postal_code' => '15820'],
            ['sub_district_name' => 'Bojongkamal (Bojong Kamal)', 'postal_code' => '15820'],
            ['sub_district_name' => 'Rancagong', 'postal_code' => '15820'],
            ['sub_district_name' => 'Kamuning (Kemuning)', 'postal_code' => '15820'],
            ['sub_district_name' => 'Cirarab', 'postal_code' => '15820'],
            ['sub_district_name' => 'Medang', 'postal_code' => '15334'],
            ['sub_district_name' => 'Cicalengka', 'postal_code' => '15336'],
            ['sub_district_name' => 'Pagedangan', 'postal_code' => '15339'],
            ['sub_district_name' => 'Cijantra', 'postal_code' => '15335'],
            ['sub_district_name' => 'Lengkong Kulon', 'postal_code' => '15331'],
            ['sub_district_name' => 'Situ Gadung', 'postal_code' => '15338'],
            ['sub_district_name' => 'Jatake', 'postal_code' => '15330'],
            ['sub_district_name' => 'Cihuni', 'postal_code' => '15332'],
            ['sub_district_name' => 'Kadu Sirung', 'postal_code' => '15337'],
            ['sub_district_name' => 'Malang Nengah', 'postal_code' => '15330'],
            ['sub_district_name' => 'Karang Tengah', 'postal_code' => '15157'],
            ['sub_district_name' => 'Cisauk', 'postal_code' => '15341'],
            ['sub_district_name' => 'Mekar Wangi (Mekarwangi)', 'postal_code' => '15340'],
            ['sub_district_name' => 'Suradita', 'postal_code' => '15343'],
            ['sub_district_name' => 'Sampora', 'postal_code' => '15345'],
            ['sub_district_name' => 'Dangdang', 'postal_code' => '15342'],
            ['sub_district_name' => 'Cibogo', 'postal_code' => '15344'],
            ['sub_district_name' => 'Benda', 'postal_code' => '15612'],
            ['sub_district_name' => 'Sukamulya (Suka Mulya)', 'postal_code' => '15612'],
            ['sub_district_name' => 'Kaliasin (Kali Asin)', 'postal_code' => '15612'],
            ['sub_district_name' => 'Buniayu (Buni Ayu)', 'postal_code' => '15612'],
            ['sub_district_name' => 'Parahu', 'postal_code' => '15612'],
            ['sub_district_name' => 'Merak', 'postal_code' => '15612'],
            ['sub_district_name' => 'Bunar', 'postal_code' => '15612'],
            ['sub_district_name' => 'Kubang', 'postal_code' => '15612'],
            ['sub_district_name' => 'Kelapa Dua', 'postal_code' => '15811'],
            ['sub_district_name' => 'Bencongan', 'postal_code' => '15811'],
            ['sub_district_name' => 'Bencongan Indah', 'postal_code' => '15811'],
            ['sub_district_name' => 'Pakulonan Barat', 'postal_code' => '15811'],
            ['sub_district_name' => 'Bojong Nangka', 'postal_code' => '15811'],
            ['sub_district_name' => 'Curug Sangerang (Curug Sangereng)', 'postal_code' => '15811'],
            ['sub_district_name' => 'Sindang Jaya', 'postal_code' => '15561'],
            ['sub_district_name' => 'Wanakerta (Wana Kerta)', 'postal_code' => '15561'],
            ['sub_district_name' => 'Sukaharja (Suka Harja)', 'postal_code' => '15561'],
            ['sub_district_name' => 'Sindangasih (Sindang Asih)', 'postal_code' => '15561'],
            ['sub_district_name' => 'Sindangpanon (Sindang Panon)', 'postal_code' => '15561'],
            ['sub_district_name' => 'Sindangsono (Sindang Sono)', 'postal_code' => '15561'],
            ['sub_district_name' => 'Badak Anom', 'postal_code' => '15561'],
            ['sub_district_name' => 'Kedaung Barat', 'postal_code' => '15521'],
            ['sub_district_name' => 'Lebak Wangi', 'postal_code' => '15521'],
            ['sub_district_name' => 'Jati Mulya', 'postal_code' => '15521'],
            ['sub_district_name' => 'Sangiang', 'postal_code' => '15521'],
            ['sub_district_name' => 'Gempol Sari', 'postal_code' => '15521'],
            ['sub_district_name' => 'Kampung Kelor', 'postal_code' => '15521'],
            ['sub_district_name' => 'Pondok Kelor', 'postal_code' => '15521'],
            ['sub_district_name' => 'Tanah Merah', 'postal_code' => '15521'],
            ['sub_district_name' => 'Solear', 'postal_code' => '15731'],
            ['sub_district_name' => 'Cikuya', 'postal_code' => '15731'],
            ['sub_district_name' => 'Cikasungka', 'postal_code' => '15731'],
            ['sub_district_name' => 'Cireundeu', 'postal_code' => '15731'],
            ['sub_district_name' => 'Cikareo', 'postal_code' => '15731'],
            ['sub_district_name' => 'Pasanggrahan', 'postal_code' => '15731'],
            ['sub_district_name' => 'Munjul', 'postal_code' => '15731'],
            ['sub_district_name' => 'Gunung Kaler', 'postal_code' => '15620'],
            ['sub_district_name' => 'Sidoko', 'postal_code' => '15620'],
            ['sub_district_name' => 'Rancagede (Ranca Gede)', 'postal_code' => '15620'],
            ['sub_district_name' => 'Kedung', 'postal_code' => '15620'],
            ['sub_district_name' => 'Cipaeh', 'postal_code' => '15620'],
            ['sub_district_name' => 'Onyam', 'postal_code' => '15620'],
            ['sub_district_name' => 'Tamiang', 'postal_code' => '15620'],
            ['sub_district_name' => 'Kandawati (Kanda Wati)', 'postal_code' => '15620'],
            ['sub_district_name' => 'Cibetok', 'postal_code' => '15620'],
            ['sub_district_name' => 'Mekar Baru', 'postal_code' => '15551'],
            ['sub_district_name' => 'Kedaung', 'postal_code' => '15551'],
            ['sub_district_name' => 'Cijeruk', 'postal_code' => '15551'],
            ['sub_district_name' => 'Waliwis', 'postal_code' => '15551'],
            ['sub_district_name' => 'Klutuk', 'postal_code' => '15551'],
            ['sub_district_name' => 'Jenggot', 'postal_code' => '15551'],
            ['sub_district_name' => 'Kosambi Dalam', 'postal_code' => '15551'],
            ['sub_district_name' => 'Gandaria (Ganda Ria)', 'postal_code' => '15551'],
            ['sub_district_name' => 'Sukarasa', 'postal_code' => '15111'],
            ['sub_district_name' => 'Sukaasih (Suka Asih)', 'postal_code' => '15111'],
            ['sub_district_name' => 'Tanah Tinggi', 'postal_code' => '15119'],
            ['sub_district_name' => 'Buaran Indah', 'postal_code' => '15119'],
            ['sub_district_name' => 'Cikokol', 'postal_code' => '15117'],
            ['sub_district_name' => 'Kelapa Indah', 'postal_code' => '15117'],
            ['sub_district_name' => 'Sukasari', 'postal_code' => '15118'],
            ['sub_district_name' => 'Babakan', 'postal_code' => '15118'],
            ['sub_district_name' => 'Keroncong', 'postal_code' => '15134'],
            ['sub_district_name' => 'Jatake', 'postal_code' => '15136'],
            ['sub_district_name' => 'Pasir Jaya', 'postal_code' => '15135'],
            ['sub_district_name' => 'Gandasari', 'postal_code' => '15137'],
            ['sub_district_name' => 'Manis Jaya', 'postal_code' => '15136'],
            ['sub_district_name' => 'Alam Jaya', 'postal_code' => '15133'],
            ['sub_district_name' => 'Batuceper (Batu Ceper)', 'postal_code' => '15122'],
            ['sub_district_name' => 'Batujaya (Batu Jaya)', 'postal_code' => '15121'],
            ['sub_district_name' => 'Poris Gaga', 'postal_code' => '15122'],
            ['sub_district_name' => 'Poris Gaga Baru', 'postal_code' => '15122'],
            ['sub_district_name' => 'Kebon Besar', 'postal_code' => '15122'],
            ['sub_district_name' => 'Batusari (Batu Sari)', 'postal_code' => '15121'],
            ['sub_district_name' => 'Poris Jaya', 'postal_code' => '15122'],
            ['sub_district_name' => 'Belendung', 'postal_code' => '15123'],
            ['sub_district_name' => 'Jurumudi', 'postal_code' => '15124'],
            ['sub_district_name' => 'Benda', 'postal_code' => '15125'],
            ['sub_district_name' => 'Pajang', 'postal_code' => '15126'],
            ['sub_district_name' => 'Jurumudi Baru', 'postal_code' => '15124'],
            ['sub_district_name' => 'Cipondoh', 'postal_code' => '15148'],
            ['sub_district_name' => 'Cipondoh Makmur', 'postal_code' => '15148'],
            ['sub_district_name' => 'Cipondoh Indah', 'postal_code' => '15148'],
            ['sub_district_name' => 'Gondrong', 'postal_code' => '15146'],
            ['sub_district_name' => 'Kenanga', 'postal_code' => '15146'],
            ['sub_district_name' => 'Petir', 'postal_code' => '15147'],
            ['sub_district_name' => 'Ketapang', 'postal_code' => '15147'],
            ['sub_district_name' => 'Poris Plawad', 'postal_code' => '15141'],
            ['sub_district_name' => 'Poris Plawad Utara', 'postal_code' => '15141'],
            ['sub_district_name' => 'Poris Plawad Indah', 'postal_code' => '15141'],
            ['sub_district_name' => 'Paninggilan', 'postal_code' => '15153'],
            ['sub_district_name' => 'Sudimara Barat', 'postal_code' => '15151'],
            ['sub_district_name' => 'Sudimara Timur', 'postal_code' => '15151'],
            ['sub_district_name' => 'Tajur', 'postal_code' => '15152'],
            ['sub_district_name' => 'Parung Serab', 'postal_code' => '15153'],
            ['sub_district_name' => 'Sudimara Jaya', 'postal_code' => '15151'],
            ['sub_district_name' => 'Sudimara Selatan', 'postal_code' => '15151'],
            ['sub_district_name' => 'Paninggilan Utara', 'postal_code' => '15153'],
            ['sub_district_name' => 'Karawaci', 'postal_code' => '15115'],
            ['sub_district_name' => 'Bojong Jaya', 'postal_code' => '15115'],
            ['sub_district_name' => 'Karawaci Baru', 'postal_code' => '15116'],
            ['sub_district_name' => 'Nusa Jaya', 'postal_code' => '15116'],
            ['sub_district_name' => 'Cimone', 'postal_code' => '15114'],
            ['sub_district_name' => 'Cimone Jaya', 'postal_code' => '15116'],
            ['sub_district_name' => 'Pabuaran', 'postal_code' => '15114'],
            ['sub_district_name' => 'Sumur Pancing (Pacing)', 'postal_code' => '15114'],
            ['sub_district_name' => 'Bugel', 'postal_code' => '15113'],
            ['sub_district_name' => 'Margasari (Marga Sari)', 'postal_code' => '15113'],
            ['sub_district_name' => 'Pabuaran Tumpeng', 'postal_code' => '15112'],
            ['sub_district_name' => 'Nambo Jaya', 'postal_code' => '15112'],
            ['sub_district_name' => 'Gerendeng', 'postal_code' => '15113'],
            ['sub_district_name' => 'Sukajadi (Suka Jadi)', 'postal_code' => '15113'],
            ['sub_district_name' => 'Pasar Baru', 'postal_code' => '15112'],
            ['sub_district_name' => 'Koang Jaya', 'postal_code' => '15112'],
            ['sub_district_name' => 'Periuk', 'postal_code' => '15131'],
            ['sub_district_name' => 'Gembor', 'postal_code' => '15133'],
            ['sub_district_name' => 'Gebang Raya', 'postal_code' => '15132'],
            ['sub_district_name' => 'Sangiang Jaya', 'postal_code' => '15132'],
            ['sub_district_name' => 'Periuk Jaya', 'postal_code' => '15131'],
            ['sub_district_name' => 'Cibodas', 'postal_code' => '15138'],
            ['sub_district_name' => 'Cibodasari (Cibodas Sari)', 'postal_code' => '15138'],
            ['sub_district_name' => 'Cibodas Baru', 'postal_code' => '15138'],
            ['sub_district_name' => 'Panunggangan Barat', 'postal_code' => '15139'],
            ['sub_district_name' => 'Uwung Jaya', 'postal_code' => '15138'],
            ['sub_district_name' => 'Jatiuwung', 'postal_code' => '15134'],
            ['sub_district_name' => 'Neglasari', 'postal_code' => '15129'],
            ['sub_district_name' => 'Karang Sari', 'postal_code' => '15121'],
            ['sub_district_name' => 'Selapajang Jaya', 'postal_code' => '15127'],
            ['sub_district_name' => 'Kedaung Wetan', 'postal_code' => '15128'],
            ['sub_district_name' => 'Mekarsari (Mekar Sari)', 'postal_code' => '15129'],
            ['sub_district_name' => 'Karang Anyar', 'postal_code' => '15121'],
            ['sub_district_name' => 'Kedaung Baru', 'postal_code' => '15128'],
            ['sub_district_name' => 'Pinang', 'postal_code' => '15145'],
            ['sub_district_name' => 'Sudimara Pinang', 'postal_code' => '15145'],
            ['sub_district_name' => 'Nerogtog', 'postal_code' => '15145'],
            ['sub_district_name' => 'Kunciran', 'postal_code' => '15144'],
            ['sub_district_name' => 'Kunciran Indah', 'postal_code' => '15144'],
            ['sub_district_name' => 'Kunciran Jaya', 'postal_code' => '15144'],
            ['sub_district_name' => 'Cipete', 'postal_code' => '15142'],
            ['sub_district_name' => 'Pakojan', 'postal_code' => '15142'],
            ['sub_district_name' => 'Panunggangan', 'postal_code' => '15143'],
            ['sub_district_name' => 'Panunggangan Utara', 'postal_code' => '15143'],
            ['sub_district_name' => 'Panunggangan Timur', 'postal_code' => '15143'],
            ['sub_district_name' => 'Karang Tengah', 'postal_code' => '15157'],
            ['sub_district_name' => 'Karang Mulya', 'postal_code' => '15157'],
            ['sub_district_name' => 'Pondok Bahar', 'postal_code' => '15159'],
            ['sub_district_name' => 'Pondok Pucung', 'postal_code' => '15158'],
            ['sub_district_name' => 'Karang Timur', 'postal_code' => '15157'],
            ['sub_district_name' => 'Padurenan (Pedurenan)', 'postal_code' => '15159'],
            ['sub_district_name' => 'Parung Jaya', 'postal_code' => '15159'],
            ['sub_district_name' => 'Larangan Utara', 'postal_code' => '15154'],
            ['sub_district_name' => 'Larangan Selatan', 'postal_code' => '15154'],
            ['sub_district_name' => 'Cipadu', 'postal_code' => '15155'],
            ['sub_district_name' => 'Kreo', 'postal_code' => '15156'],
            ['sub_district_name' => 'Larangan Indah', 'postal_code' => '15154'],
            ['sub_district_name' => 'Gaga', 'postal_code' => '15154'],
            ['sub_district_name' => 'Cipadu Jaya', 'postal_code' => '15155'],
            ['sub_district_name' => 'Kreo Selatan', 'postal_code' => '15156'],
        ];

        foreach ($data as $item) {
            $sub = SubDistrict::where('name', $item['sub_district_name'])->first();
            if ($sub) {
                for ($i = 1; $i <= rand(3, 5); $i++) {
                    Neighborhood::create([
                        'sub_district_id' => $sub->id,
                        'rt' => str_pad($i, 3, '0', STR_PAD_LEFT),
                        'rw' => str_pad(rand(1, 5), 3, '0', STR_PAD_LEFT),
                        'postal_code' => $item['postal_code']
                    ]);
                }
            }
        }
    }
}
