<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\District;
use App\Models\SubDistrict;

use Illuminate\Database\Seeder;

class TangerangSeeder extends Seeder
{
    public function run(): void
    {
        $city_0 = City::create(['name' => 'Kota Tangerang']);
        $city_1 = City::create(['name' => 'Kabupaten Tangerang']);

        $district_0 = District::create(['name' => 'Tangerang', 'city_id' => $city_0->id]);
        $district_1 = District::create(['name' => 'Jatiuwung', 'city_id' => $city_0->id]);
        $district_2 = District::create(['name' => 'Batuceper', 'city_id' => $city_0->id]);
        $district_3 = District::create(['name' => 'Benda', 'city_id' => $city_0->id]);
        $district_4 = District::create(['name' => 'Cipondoh', 'city_id' => $city_0->id]);
        $district_5 = District::create(['name' => 'Ciledug', 'city_id' => $city_0->id]);
        $district_6 = District::create(['name' => 'Karawaci', 'city_id' => $city_0->id]);
        $district_7 = District::create(['name' => 'Periuk', 'city_id' => $city_0->id]);
        $district_8 = District::create(['name' => 'Cibodas', 'city_id' => $city_0->id]);
        $district_9 = District::create(['name' => 'Neglasari', 'city_id' => $city_0->id]);
        $district_10 = District::create(['name' => 'Pinang (Penang)', 'city_id' => $city_0->id]);
        $district_11 = District::create(['name' => 'Karang Tengah', 'city_id' => $city_0->id]);
        $district_12 = District::create(['name' => 'Larangan', 'city_id' => $city_0->id]);
        $district_13 = District::create(['name' => 'Balaraja', 'city_id' => $city_1->id]);
        $district_14 = District::create(['name' => 'Jayanti', 'city_id' => $city_1->id]);
        $district_15 = District::create(['name' => 'Tigaraksa', 'city_id' => $city_1->id]);
        $district_16 = District::create(['name' => 'Jambe', 'city_id' => $city_1->id]);
        $district_17 = District::create(['name' => 'Cisoka', 'city_id' => $city_1->id]);
        $district_18 = District::create(['name' => 'Kresek', 'city_id' => $city_1->id]);
        $district_19 = District::create(['name' => 'Kronjo', 'city_id' => $city_1->id]);
        $district_20 = District::create(['name' => 'Mauk', 'city_id' => $city_1->id]);
        $district_21 = District::create(['name' => 'Kemiri', 'city_id' => $city_1->id]);
        $district_22 = District::create(['name' => 'Sukadiri', 'city_id' => $city_1->id]);
        $district_23 = District::create(['name' => 'Rajeg', 'city_id' => $city_1->id]);
        $district_24 = District::create(['name' => 'Pasar Kemis', 'city_id' => $city_1->id]);
        $district_25 = District::create(['name' => 'Teluknaga', 'city_id' => $city_1->id]);
        $district_26 = District::create(['name' => 'Kosambi', 'city_id' => $city_1->id]);
        $district_27 = District::create(['name' => 'Pakuhaji', 'city_id' => $city_1->id]);
        $district_28 = District::create(['name' => 'Sepatan', 'city_id' => $city_1->id]);
        $district_29 = District::create(['name' => 'Curug', 'city_id' => $city_1->id]);
        $district_30 = District::create(['name' => 'Cikupa', 'city_id' => $city_1->id]);
        $district_31 = District::create(['name' => 'Panongan', 'city_id' => $city_1->id]);
        $district_32 = District::create(['name' => 'Legok', 'city_id' => $city_1->id]);
        $district_33 = District::create(['name' => 'Pagedangan', 'city_id' => $city_1->id]);
        $district_34 = District::create(['name' => 'Cisauk', 'city_id' => $city_1->id]);
        $district_35 = District::create(['name' => 'Sukamulya', 'city_id' => $city_1->id]);
        $district_36 = District::create(['name' => 'Kelapa Dua', 'city_id' => $city_1->id]);
        $district_37 = District::create(['name' => 'Sindang Jaya', 'city_id' => $city_1->id]);
        $district_38 = District::create(['name' => 'Sepatan Timur', 'city_id' => $city_1->id]);
        $district_39 = District::create(['name' => 'Solear', 'city_id' => $city_1->id]);
        $district_40 = District::create(['name' => 'Gunung Kaler', 'city_id' => $city_1->id]);
        $district_41 = District::create(['name' => 'Mekar Baru', 'city_id' => $city_1->id]);
        SubDistrict::create(['name' => 'Sukarasa', 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Sukaasih', 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Tanah Tinggi', 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Buaran Indah', 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Cikokol', 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Kelapa Indah', 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Sukasari', 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Babakan', 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Keroncong', 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Jatake', 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Pasir Jaya', 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Gandasari', 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Manis Jaya', 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Alam Jaya', 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Batuceper', 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Batujaya', 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Poris Gaga', 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Poris Gaga Baru', 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Kebon Besar', 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Batu Sari', 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Poris Jaya', 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Belendung', 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Jurumudi', 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Benda', 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Pajang', 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Jurumudi Baru', 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Cipondoh', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Cipondoh Makmur', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Cipondoh Indah', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Gondrong', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Kenanga', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Petir', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Ketapang', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Poris Plawad', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Poris Plawad Utara', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Poris Plawad Indah', 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Paninggilan', 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Sudimara Barat', 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Sudimara Timur', 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Tajur', 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Parung Serab', 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Sudimara Jaya', 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Sudimara Selatan', 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Paninggilan Utara', 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Karawaci', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Bojong Jaya', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Karawaci Baru', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Nusa Jaya', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Cimone', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Cimone Jaya', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Pabuaran', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Sumur Pancing', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Bugel', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Margasari', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Pabuaran Tumpeng', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Nambo Jaya', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Gerendeng', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Sukajadi', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Pasar Baru', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Koang Jaya', 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Periuk', 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Gembor', 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Gebang Jaya', 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Sangiang Jaya', 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Periuk Jaya', 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Cibodas', 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Cibodasari', 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Cibodas Baru', 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Panunggangan Barat', 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Uwung Jaya', 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Jatiuwung', 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Neglasari', 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Karang Sari', 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Selapajang Jaya', 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Kedaung Wetan', 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Mekarsari', 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Karang Anyar', 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Kedaung Baru', 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Pinang', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Sudimara Pinang', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Nerogtog', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Kunciran', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Kunciran Indah', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Kunciran Jaya', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Cipete', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Pakojan', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Panunggangan', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Panunggangan Utara', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Panunggangan Timur', 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Karang Tengah', 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Karang Mulya', 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Pondok Bahar', 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Pondok Pucung', 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Karang Timur', 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Padurenan', 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Parung Jaya', 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Larangan Utara', 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Larangan Selatan', 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Cipadu', 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Kreo', 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Larangan Indah', 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Gaga', 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Cipadu Jaya', 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Kreo Selatan', 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Balaraja', 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Cangkudu', 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Talagasari', 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Tobat', 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Sentul', 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Gembong', 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Sukamurni (Suka Murni)', 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Saga', 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Sentul Jaya', 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Pangkat', 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Pabuaran', 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Pasir Muncang', 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Sumur Bandung', 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Jayanti', 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Dangdeur (Dang Deur)', 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Cikande', 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Pasir Gintung', 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Tigaraksa', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Kadu Agung', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Pasir Bolang', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Matagara (Mata Gara)', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Pasir Nangka', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Pete', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Tegalsari', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Pematang', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Cisereh', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Margasari (Marga Sari)', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Cileles', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Sodong', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Tapos', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Bantar Panjang', 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Sukamanah (Suka Manah)', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Jambe', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Tipar Raya (Tipar Jaya / Tiparraya)', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Taban', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Daru', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Kutruk', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Ranca Buaya (Rancabuaya)', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Mekarsari', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Ancol Pasir', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Pasir Barat', 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Cisoka', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Caringin', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Selapajang', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Sukatani', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Bojong Loa (Bojongloa)', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Cibugel', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Cempaka', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Carenang', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Karang Harja (Karangharja)', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Jeungjing (Jeung Jing)', 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Pasir Ampo', 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Rancailat (Ranca Ilat)', 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Kemuning', 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Renged', 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Talok', 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Koper', 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Jengkol', 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Patrasana (Patra Sana)', 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Kresek', 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Kronjo', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pagenjahan', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pasir', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Muncung', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pagedangan Ilir', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pagedangan Udik', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pasilian', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Bakung', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Blukbuk', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Cirumpak', 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Mauk Timur', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Mauk Barat', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Tegal Kunir Kidul', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Tegal Kunir Lor', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Sasak', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Gunung Sari', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Kedung Dalem', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Marga Mulya', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Tanjung Anom', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Jatiwaringin (Jati Waringin)', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Banyu Asih', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Ketapang', 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Patramanggala (Patra Manggala)', 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Karang Anyar', 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Lontar', 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Kemiri', 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Ranca Labuh', 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Klebet (Kjlebet / Kelebet)', 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Legok Suka Maju (Legok Sula Maju)', 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Sukadiri', 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Buaran Jati', 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Rawa Kidang', 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Pekayon', 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Karang Serang', 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Kosambi', 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Mekar Kondang', 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Gintung', 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Sukatani (Suka Tani)', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Rajeg', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Rajeg Mulya (Rajegmulya)', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Pangarengan', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Jambu Karya', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Lembangsari (Lembang Sari)', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Sukamanah (Suka Manah)', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Tanjakan', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Tanjakan Mekar', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Sukasari (Suka Sari)', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Ranca Bango', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Daon', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Mekarsari', 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Sindangsari (Sindang Sari)', 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Kutabumi (Kuta Bumi)', 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Kuta Jaya', 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Kuta Baru', 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Pasar Kemis', 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Sukamantri', 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Pangadegan', 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Gelam Jaya', 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Suka Asih (Sukaasih)', 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Teluknaga (Teluk Naga)', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Bojong Renged', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Babakan Asem', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Keboncau (Kebon Cau)', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Pangkalan', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Kampung Melayu Timur', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Kampung Melayu Barat', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Muara', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Lemo', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Tanjung Pasir', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Tegal Angus', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Tanjung Burung', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Kampung Besar', 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Kosambi Barat', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Salembaran Jaya (Salembaran Raya)', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Dadap', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Kosambi Timur', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Salembaran Jati', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Ranga Rengas (Rawa Rengas)', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Rawa Burung', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Cengklong', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Belimbing', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Jati Mulya (Jatimulya)', 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Pakuhaji', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Paku Alam', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Bunisari (Bonasari)', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Rawa Boni', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Buaran Mangga', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Buaran Bambu', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Kalibaru', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Kohod', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Kramat', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Sukawali', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Surya Bahari', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Kiara Payung', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Laksana', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Gaga', 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Sepatan', 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Karet', 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Kayu Agung', 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Kayu Bongkok', 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Pondok Jaya', 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Pisangan Jaya', 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Mekar Jaya', 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Sarakan', 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Curug Kulon', 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Sukabakti (Suka Bakti)', 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Binong', 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Curug Wetan', 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Kadu', 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Kadu Jaya', 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Cukanggalih (Cukang Galih)', 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Sukamulya (Suka Mulya)', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Bunder', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Cibadak', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Talaga', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Talagasari (Talaga Sari)', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Dukuh', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Cikupa', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Sukanagara (Suka Nagara)', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Bitung Jaya', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Pasir Gadung', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Sukadamai (Suka Damai)', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Pasir Jaya', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Budi Mulya', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Bojong', 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Mekar Bakti', 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Ranca Iyuh', 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Peusar', 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Ranca Kalapa', 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Serdang Kulon', 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Mekar Jaya', 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Ciakar', 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Panongan', 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Babakan', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Caringin', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Serdang Wetan', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Babat', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Ciangir', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Legok', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Palasari (Pala Sari)', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Bojongkamal (Bojong Kamal)', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Rancagong', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Kamuning (Kemuning)', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Cirarab', 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Medang', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Cicalengka', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Pagedangan', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Cijantra', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Lengkong Kulon', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Situ Gadung', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Jatake', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Cihuni', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Kadu Sirung', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Malang Nengah', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Karang Tengah', 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Cisauk', 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Mekar Wangi (Mekarwangi)', 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Suradita', 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Sampora', 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Dangdang', 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Cibogo', 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Benda', 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Sukamulya (Suka Mulya)', 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Kaliasin (Kali Asin)', 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Buniayu (Buni Ayu)', 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Parahu', 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Merak', 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Bunar', 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Kubang', 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Kelapa Dua', 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Bencongan', 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Bencongan Indah', 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Pakulonan Barat', 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Bojong Nangka', 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Curug Sangerang (Curug Sangereng)', 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Sindang Jaya', 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Wanakerta (Wana Kerta)', 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Sukaharja (Suka Harja)', 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Sindangasih (Sindang Asih)', 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Sindangpanon (Sindang Panon)', 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Sindangsono (Sindang Sono)', 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Badak Anom', 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Kedaung Barat', 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Lebak Wangi', 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Jati Mulya', 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Sangiang', 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Gempol Sari', 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Kampung Kelor', 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Pondok Kelor', 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Tanah Merah', 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Solear', 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Cikuya', 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Cikasungka', 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Cireundeu', 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Cikareo', 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Pasanggrahan', 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Munjul', 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Gunung Kaler', 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Sidoko', 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Rancagede (Ranca Gede)', 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Kedung', 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Cipaeh', 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Onyam', 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Tamiang', 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Kandawati (Kanda Wati)', 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Cibetok', 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Mekar Baru', 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Kedaung', 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Cijeruk', 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Waliwis', 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Klutuk', 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Jenggot', 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Kosambi Dalam', 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Gandaria (Ganda Ria)', 'district_id' => $district_41->id]);
    }
}
