<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\District;
use App\Models\SubDistrict;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class TangerangSeeder extends Seeder
{
    public function run(): void
    {
        $city_0 = City::create(['name' => 'Kota Tangerang', 'slug' => Str::slug('Kota Tangerang')]);
        $city_1 = City::create(['name' => 'Kabupaten Tangerang', 'slug' => Str::slug('Kabupaten Tangerang')]);

        $district_0 = District::create(['name' => 'Tangerang', 'slug' => Str::slug('Tangerang'), 'city_id' => $city_0->id]);
        $district_1 = District::create(['name' => 'Jatiuwung', 'slug' => Str::slug('Jatiuwung'), 'city_id' => $city_0->id]);
        $district_2 = District::create(['name' => 'Batuceper', 'slug' => Str::slug('Batuceper'), 'city_id' => $city_0->id]);
        $district_3 = District::create(['name' => 'Benda', 'slug' => Str::slug('Benda'), 'city_id' => $city_0->id]);
        $district_4 = District::create(['name' => 'Cipondoh', 'slug' => Str::slug('Cipondoh'), 'city_id' => $city_0->id]);
        $district_5 = District::create(['name' => 'Ciledug', 'slug' => Str::slug('Ciledug'), 'city_id' => $city_0->id]);
        $district_6 = District::create(['name' => 'Karawaci', 'slug' => Str::slug('Karawaci'), 'city_id' => $city_0->id]);
        $district_7 = District::create(['name' => 'Periuk', 'slug' => Str::slug('Periuk'), 'city_id' => $city_0->id]);
        $district_8 = District::create(['name' => 'Cibodas', 'slug' => Str::slug('Cibodas'), 'city_id' => $city_0->id]);
        $district_9 = District::create(['name' => 'Neglasari', 'slug' => Str::slug('Neglasari'), 'city_id' => $city_0->id]);
        $district_10 = District::create(['name' => 'Pinang (Penang)', 'slug' => Str::slug('Pinang (Penang)'), 'city_id' => $city_0->id]);
        $district_11 = District::create(['name' => 'Karang Tengah', 'slug' => Str::slug('Karang Tengah'), 'city_id' => $city_0->id]);
        $district_12 = District::create(['name' => 'Larangan', 'slug' => Str::slug('Larangan'), 'city_id' => $city_0->id]);
        $district_13 = District::create(['name' => 'Balaraja', 'slug' => Str::slug('Balaraja'), 'city_id' => $city_1->id]);
        $district_14 = District::create(['name' => 'Jayanti', 'slug' => Str::slug('Jayanti'), 'city_id' => $city_1->id]);
        $district_15 = District::create(['name' => 'Tigaraksa', 'slug' => Str::slug('Tigaraksa'), 'city_id' => $city_1->id]);
        $district_16 = District::create(['name' => 'Jambe', 'slug' => Str::slug('Jambe'), 'city_id' => $city_1->id]);
        $district_17 = District::create(['name' => 'Cisoka', 'slug' => Str::slug('Cisoka'), 'city_id' => $city_1->id]);
        $district_18 = District::create(['name' => 'Kresek', 'slug' => Str::slug('Kresek'), 'city_id' => $city_1->id]);
        $district_19 = District::create(['name' => 'Kronjo', 'slug' => Str::slug('Kronjo'), 'city_id' => $city_1->id]);
        $district_20 = District::create(['name' => 'Mauk', 'slug' => Str::slug('Mauk'), 'city_id' => $city_1->id]);
        $district_21 = District::create(['name' => 'Kemiri', 'slug' => Str::slug('Kemiri'), 'city_id' => $city_1->id]);
        $district_22 = District::create(['name' => 'Sukadiri', 'slug' => Str::slug('Sukadiri'), 'city_id' => $city_1->id]);
        $district_23 = District::create(['name' => 'Rajeg', 'slug' => Str::slug('Rajeg'), 'city_id' => $city_1->id]);
        $district_24 = District::create(['name' => 'Pasar Kemis', 'slug' => Str::slug('Pasar Kemis'), 'city_id' => $city_1->id]);
        $district_25 = District::create(['name' => 'Teluknaga', 'slug' => Str::slug('Teluknaga'), 'city_id' => $city_1->id]);
        $district_26 = District::create(['name' => 'Kosambi', 'slug' => Str::slug('Kosambi'), 'city_id' => $city_1->id]);
        $district_27 = District::create(['name' => 'Pakuhaji', 'slug' => Str::slug('Pakuhaji'), 'city_id' => $city_1->id]);
        $district_28 = District::create(['name' => 'Sepatan', 'slug' => Str::slug('Sepatan'), 'city_id' => $city_1->id]);
        $district_29 = District::create(['name' => 'Curug', 'slug' => Str::slug('Curug'), 'city_id' => $city_1->id]);
        $district_30 = District::create(['name' => 'Cikupa', 'slug' => Str::slug('Cikupa'), 'city_id' => $city_1->id]);
        $district_31 = District::create(['name' => 'Panongan', 'slug' => Str::slug('Panongan'), 'city_id' => $city_1->id]);
        $district_32 = District::create(['name' => 'Legok', 'slug' => Str::slug('Legok'), 'city_id' => $city_1->id]);
        $district_33 = District::create(['name' => 'Pagedangan', 'slug' => Str::slug('Pagedangan'), 'city_id' => $city_1->id]);
        $district_34 = District::create(['name' => 'Cisauk', 'slug' => Str::slug('Cisauk'), 'city_id' => $city_1->id]);
        $district_35 = District::create(['name' => 'Sukamulya', 'slug' => Str::slug('Sukamulya'), 'city_id' => $city_1->id]);
        $district_36 = District::create(['name' => 'Kelapa Dua', 'slug' => Str::slug('Kelapa Dua'), 'city_id' => $city_1->id]);
        $district_37 = District::create(['name' => 'Sindang Jaya', 'slug' => Str::slug('Sindang Jaya'), 'city_id' => $city_1->id]);
        $district_38 = District::create(['name' => 'Sepatan Timur', 'slug' => Str::slug('Sepatan Timur'), 'city_id' => $city_1->id]);
        $district_39 = District::create(['name' => 'Solear', 'slug' => Str::slug('Solear'), 'city_id' => $city_1->id]);
        $district_40 = District::create(['name' => 'Gunung Kaler', 'slug' => Str::slug('Gunung Kaler'), 'city_id' => $city_1->id]);
        $district_41 = District::create(['name' => 'Mekar Baru', 'slug' => Str::slug('Mekar Baru'), 'city_id' => $city_1->id]);
        SubDistrict::create(['name' => 'Sukarasa', 'slug' => Str::slug('Sukarasa'), 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Sukaasih', 'slug' => Str::slug('Sukaasih'), 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Tanah Tinggi', 'slug' => Str::slug('Tanah Tinggi'), 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Buaran Indah', 'slug' => Str::slug('Buaran Indah'), 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Cikokol', 'slug' => Str::slug('Cikokol'), 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Kelapa Indah', 'slug' => Str::slug('Kelapa Indah'), 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Sukasari', 'slug' => Str::slug('Sukasari'), 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Babakan', 'slug' => Str::slug('Babakan'), 'district_id' => $district_0->id]);
        SubDistrict::create(['name' => 'Keroncong', 'slug' => Str::slug('Keroncong'), 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Jatake', 'slug' => Str::slug('Jatake'), 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Pasir Jaya', 'slug' => Str::slug('Pasir Jaya'), 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Gandasari', 'slug' => Str::slug('Gandasari'), 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Manis Jaya', 'slug' => Str::slug('Manis Jaya'), 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Alam Jaya', 'slug' => Str::slug('Alam Jaya'), 'district_id' => $district_1->id]);
        SubDistrict::create(['name' => 'Batuceper', 'slug' => Str::slug('Batuceper'), 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Batujaya', 'slug' => Str::slug('Batujaya'), 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Poris Gaga', 'slug' => Str::slug('Poris Gaga'), 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Poris Gaga Baru', 'slug' => Str::slug('Poris Gaga Baru'), 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Kebon Besar', 'slug' => Str::slug('Kebon Besar'), 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Batu Sari', 'slug' => Str::slug('Batu Sari'), 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Poris Jaya', 'slug' => Str::slug('Poris Jaya'), 'district_id' => $district_2->id]);
        SubDistrict::create(['name' => 'Belendung', 'slug' => Str::slug('Belendung'), 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Jurumudi', 'slug' => Str::slug('Jurumudi'), 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Benda', 'slug' => Str::slug('Benda'), 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Pajang', 'slug' => Str::slug('Pajang'), 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Jurumudi Baru', 'slug' => Str::slug('Jurumudi Baru'), 'district_id' => $district_3->id]);
        SubDistrict::create(['name' => 'Cipondoh', 'slug' => Str::slug('Cipondoh'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Cipondoh Makmur', 'slug' => Str::slug('Cipondoh Makmur'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Cipondoh Indah', 'slug' => Str::slug('Cipondoh Indah'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Gondrong', 'slug' => Str::slug('Gondrong'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Kenanga', 'slug' => Str::slug('Kenanga'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Petir', 'slug' => Str::slug('Petir'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Ketapang', 'slug' => Str::slug('Ketapang'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Poris Plawad', 'slug' => Str::slug('Poris Plawad'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Poris Plawad Utara', 'slug' => Str::slug('Poris Plawad Utara'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Poris Plawad Indah', 'slug' => Str::slug('Poris Plawad Indah'), 'district_id' => $district_4->id]);
        SubDistrict::create(['name' => 'Paninggilan', 'slug' => Str::slug('Paninggilan'), 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Sudimara Barat', 'slug' => Str::slug('Sudimara Barat'), 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Sudimara Timur', 'slug' => Str::slug('Sudimara Timur'), 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Tajur', 'slug' => Str::slug('Tajur'), 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Parung Serab', 'slug' => Str::slug('Parung Serab'), 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Sudimara Jaya', 'slug' => Str::slug('Sudimara Jaya'), 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Sudimara Selatan', 'slug' => Str::slug('Sudimara Selatan'), 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Paninggilan Utara', 'slug' => Str::slug('Paninggilan Utara'), 'district_id' => $district_5->id]);
        SubDistrict::create(['name' => 'Karawaci', 'slug' => Str::slug('Karawaci'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Bojong Jaya', 'slug' => Str::slug('Bojong Jaya'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Karawaci Baru', 'slug' => Str::slug('Karawaci Baru'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Nusa Jaya', 'slug' => Str::slug('Nusa Jaya'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Cimone', 'slug' => Str::slug('Cimone'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Cimone Jaya', 'slug' => Str::slug('Cimone Jaya'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Pabuaran', 'slug' => Str::slug('Pabuaran'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Sumur Pancing', 'slug' => Str::slug('Sumur Pancing'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Bugel', 'slug' => Str::slug('Bugel'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Margasari', 'slug' => Str::slug('Margasari'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Pabuaran Tumpeng', 'slug' => Str::slug('Pabuaran Tumpeng'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Nambo Jaya', 'slug' => Str::slug('Nambo Jaya'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Gerendeng', 'slug' => Str::slug('Gerendeng'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Sukajadi', 'slug' => Str::slug('Sukajadi'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Pasar Baru', 'slug' => Str::slug('Pasar Baru'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Koang Jaya', 'slug' => Str::slug('Koang Jaya'), 'district_id' => $district_6->id]);
        SubDistrict::create(['name' => 'Periuk', 'slug' => Str::slug('Periuk'), 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Gembor', 'slug' => Str::slug('Gembor'), 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Gebang Jaya', 'slug' => Str::slug('Gebang Jaya'), 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Sangiang Jaya', 'slug' => Str::slug('Sangiang Jaya'), 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Periuk Jaya', 'slug' => Str::slug('Periuk Jaya'), 'district_id' => $district_7->id]);
        SubDistrict::create(['name' => 'Cibodas', 'slug' => Str::slug('Cibodas'), 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Cibodasari', 'slug' => Str::slug('Cibodasari'), 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Cibodas Baru', 'slug' => Str::slug('Cibodas Baru'), 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Panunggangan Barat', 'slug' => Str::slug('Panunggangan Barat'), 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Uwung Jaya', 'slug' => Str::slug('Uwung Jaya'), 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Jatiuwung', 'slug' => Str::slug('Jatiuwung'), 'district_id' => $district_8->id]);
        SubDistrict::create(['name' => 'Neglasari', 'slug' => Str::slug('Neglasari'), 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Karang Sari', 'slug' => Str::slug('Karang Sari'), 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Selapajang Jaya', 'slug' => Str::slug('Selapajang Jaya'), 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Kedaung Wetan', 'slug' => Str::slug('Kedaung Wetan'), 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Mekarsari', 'slug' => Str::slug('Mekarsari'), 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Karang Anyar', 'slug' => Str::slug('Karang Anyar'), 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Kedaung Baru', 'slug' => Str::slug('Kedaung Baru'), 'district_id' => $district_9->id]);
        SubDistrict::create(['name' => 'Pinang', 'slug' => Str::slug('Pinang'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Sudimara Pinang', 'slug' => Str::slug('Sudimara Pinang'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Nerogtog', 'slug' => Str::slug('Nerogtog'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Kunciran', 'slug' => Str::slug('Kunciran'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Kunciran Indah', 'slug' => Str::slug('Kunciran Indah'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Kunciran Jaya', 'slug' => Str::slug('Kunciran Jaya'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Cipete', 'slug' => Str::slug('Cipete'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Pakojan', 'slug' => Str::slug('Pakojan'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Panunggangan', 'slug' => Str::slug('Panunggangan'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Panunggangan Utara', 'slug' => Str::slug('Panunggangan Utara'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Panunggangan Timur', 'slug' => Str::slug('Panunggangan Timur'), 'district_id' => $district_10->id]);
        SubDistrict::create(['name' => 'Karang Tengah', 'slug' => Str::slug('Karang Tengah'), 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Karang Mulya', 'slug' => Str::slug('Karang Mulya'), 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Pondok Bahar', 'slug' => Str::slug('Pondok Bahar'), 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Pondok Pucung', 'slug' => Str::slug('Pondok Pucung'), 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Karang Timur', 'slug' => Str::slug('Karang Timur'), 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Padurenan', 'slug' => Str::slug('Padurenan'), 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Parung Jaya', 'slug' => Str::slug('Parung Jaya'), 'district_id' => $district_11->id]);
        SubDistrict::create(['name' => 'Larangan Utara', 'slug' => Str::slug('Larangan Utara'), 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Larangan Selatan', 'slug' => Str::slug('Larangan Selatan'), 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Cipadu', 'slug' => Str::slug('Cipadu'), 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Kreo', 'slug' => Str::slug('Kreo'), 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Larangan Indah', 'slug' => Str::slug('Larangan Indah'), 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Gaga', 'slug' => Str::slug('Gaga'), 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Cipadu Jaya', 'slug' => Str::slug('Cipadu Jaya'), 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Kreo Selatan', 'slug' => Str::slug('Kreo Selatan'), 'district_id' => $district_12->id]);
        SubDistrict::create(['name' => 'Balaraja', 'slug' => Str::slug('Balaraja'), 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Cangkudu', 'slug' => Str::slug('Cangkudu'), 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Talagasari', 'slug' => Str::slug('Talagasari'), 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Tobat', 'slug' => Str::slug('Tobat'), 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Sentul', 'slug' => Str::slug('Sentul'), 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Gembong', 'slug' => Str::slug('Gembong'), 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Sukamurni (Suka Murni)', 'slug' => Str::slug('Sukamurni (Suka Murni)'), 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Saga', 'slug' => Str::slug('Saga'), 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Sentul Jaya', 'slug' => Str::slug('Sentul Jaya'), 'district_id' => $district_13->id]);
        SubDistrict::create(['name' => 'Pangkat', 'slug' => Str::slug('Pangkat'), 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Pabuaran', 'slug' => Str::slug('Pabuaran'), 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Pasir Muncang', 'slug' => Str::slug('Pasir Muncang'), 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Sumur Bandung', 'slug' => Str::slug('Sumur Bandung'), 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Jayanti', 'slug' => Str::slug('Jayanti'), 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Dangdeur (Dang Deur)', 'slug' => Str::slug('Dangdeur (Dang Deur)'), 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Cikande', 'slug' => Str::slug('Cikande'), 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Pasir Gintung', 'slug' => Str::slug('Pasir Gintung'), 'district_id' => $district_14->id]);
        SubDistrict::create(['name' => 'Tigaraksa', 'slug' => Str::slug('Tigaraksa'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Kadu Agung', 'slug' => Str::slug('Kadu Agung'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Pasir Bolang', 'slug' => Str::slug('Pasir Bolang'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Matagara (Mata Gara)', 'slug' => Str::slug('Matagara (Mata Gara)'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Pasir Nangka', 'slug' => Str::slug('Pasir Nangka'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Pete', 'slug' => Str::slug('Pete'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Tegalsari', 'slug' => Str::slug('Tegalsari'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Pematang', 'slug' => Str::slug('Pematang'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Cisereh', 'slug' => Str::slug('Cisereh'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Margasari (Marga Sari)', 'slug' => Str::slug('Margasari (Marga Sari)'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Cileles', 'slug' => Str::slug('Cileles'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Sodong', 'slug' => Str::slug('Sodong'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Tapos', 'slug' => Str::slug('Tapos'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Bantar Panjang', 'slug' => Str::slug('Bantar Panjang'), 'district_id' => $district_15->id]);
        SubDistrict::create(['name' => 'Sukamanah (Suka Manah)', 'slug' => Str::slug('Sukamanah (Suka Manah)'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Jambe', 'slug' => Str::slug('Jambe'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Tipar Raya (Tipar Jaya / Tiparraya)', 'slug' => Str::slug('Tipar Raya (Tipar Jaya / Tiparraya)'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Taban', 'slug' => Str::slug('Taban'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Daru', 'slug' => Str::slug('Daru'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Kutruk', 'slug' => Str::slug('Kutruk'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Ranca Buaya (Rancabuaya)', 'slug' => Str::slug('Ranca Buaya (Rancabuaya)'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Mekarsari', 'slug' => Str::slug('Mekarsari'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Ancol Pasir', 'slug' => Str::slug('Ancol Pasir'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Pasir Barat', 'slug' => Str::slug('Pasir Barat'), 'district_id' => $district_16->id]);
        SubDistrict::create(['name' => 'Cisoka', 'slug' => Str::slug('Cisoka'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Caringin', 'slug' => Str::slug('Caringin'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Selapajang', 'slug' => Str::slug('Selapajang'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Sukatani', 'slug' => Str::slug('Sukatani'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Bojong Loa (Bojongloa)', 'slug' => Str::slug('Bojong Loa (Bojongloa)'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Cibugel', 'slug' => Str::slug('Cibugel'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Cempaka', 'slug' => Str::slug('Cempaka'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Carenang', 'slug' => Str::slug('Carenang'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Karang Harja (Karangharja)', 'slug' => Str::slug('Karang Harja (Karangharja)'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Jeungjing (Jeung Jing)', 'slug' => Str::slug('Jeungjing (Jeung Jing)'), 'district_id' => $district_17->id]);
        SubDistrict::create(['name' => 'Pasir Ampo', 'slug' => Str::slug('Pasir Ampo'), 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Rancailat (Ranca Ilat)', 'slug' => Str::slug('Rancailat (Ranca Ilat)'), 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Kemuning', 'slug' => Str::slug('Kemuning'), 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Renged', 'slug' => Str::slug('Renged'), 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Talok', 'slug' => Str::slug('Talok'), 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Koper', 'slug' => Str::slug('Koper'), 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Jengkol', 'slug' => Str::slug('Jengkol'), 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Patrasana (Patra Sana)', 'slug' => Str::slug('Patrasana (Patra Sana)'), 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Kresek', 'slug' => Str::slug('Kresek'), 'district_id' => $district_18->id]);
        SubDistrict::create(['name' => 'Kronjo', 'slug' => Str::slug('Kronjo'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pagenjahan', 'slug' => Str::slug('Pagenjahan'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pasir', 'slug' => Str::slug('Pasir'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Muncung', 'slug' => Str::slug('Muncung'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pagedangan Ilir', 'slug' => Str::slug('Pagedangan Ilir'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pagedangan Udik', 'slug' => Str::slug('Pagedangan Udik'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Pasilian', 'slug' => Str::slug('Pasilian'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Bakung', 'slug' => Str::slug('Bakung'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Blukbuk', 'slug' => Str::slug('Blukbuk'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Cirumpak', 'slug' => Str::slug('Cirumpak'), 'district_id' => $district_19->id]);
        SubDistrict::create(['name' => 'Mauk Timur', 'slug' => Str::slug('Mauk Timur'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Mauk Barat', 'slug' => Str::slug('Mauk Barat'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Tegal Kunir Kidul', 'slug' => Str::slug('Tegal Kunir Kidul'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Tegal Kunir Lor', 'slug' => Str::slug('Tegal Kunir Lor'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Sasak', 'slug' => Str::slug('Sasak'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Gunung Sari', 'slug' => Str::slug('Gunung Sari'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Kedung Dalem', 'slug' => Str::slug('Kedung Dalem'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Marga Mulya', 'slug' => Str::slug('Marga Mulya'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Tanjung Anom', 'slug' => Str::slug('Tanjung Anom'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Jatiwaringin (Jati Waringin)', 'slug' => Str::slug('Jatiwaringin (Jati Waringin)'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Banyu Asih', 'slug' => Str::slug('Banyu Asih'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Ketapang', 'slug' => Str::slug('Ketapang'), 'district_id' => $district_20->id]);
        SubDistrict::create(['name' => 'Patramanggala (Patra Manggala)', 'slug' => Str::slug('Patramanggala (Patra Manggala)'), 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Karang Anyar', 'slug' => Str::slug('Karang Anyar'), 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Lontar', 'slug' => Str::slug('Lontar'), 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Kemiri', 'slug' => Str::slug('Kemiri'), 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Ranca Labuh', 'slug' => Str::slug('Ranca Labuh'), 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Klebet (Kjlebet / Kelebet)', 'slug' => Str::slug('Klebet (Kjlebet / Kelebet)'), 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Legok Suka Maju (Legok Sula Maju)', 'slug' => Str::slug('Legok Suka Maju (Legok Sula Maju)'), 'district_id' => $district_21->id]);
        SubDistrict::create(['name' => 'Sukadiri', 'slug' => Str::slug('Sukadiri'), 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Buaran Jati', 'slug' => Str::slug('Buaran Jati'), 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Rawa Kidang', 'slug' => Str::slug('Rawa Kidang'), 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Pekayon', 'slug' => Str::slug('Pekayon'), 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Karang Serang', 'slug' => Str::slug('Karang Serang'), 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Kosambi', 'slug' => Str::slug('Kosambi'), 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Mekar Kondang', 'slug' => Str::slug('Mekar Kondang'), 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Gintung', 'slug' => Str::slug('Gintung'), 'district_id' => $district_22->id]);
        SubDistrict::create(['name' => 'Sukatani (Suka Tani)', 'slug' => Str::slug('Sukatani (Suka Tani)'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Rajeg', 'slug' => Str::slug('Rajeg'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Rajeg Mulya (Rajegmulya)', 'slug' => Str::slug('Rajeg Mulya (Rajegmulya)'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Pangarengan', 'slug' => Str::slug('Pangarengan'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Jambu Karya', 'slug' => Str::slug('Jambu Karya'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Lembangsari (Lembang Sari)', 'slug' => Str::slug('Lembangsari (Lembang Sari)'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Sukamanah (Suka Manah)', 'slug' => Str::slug('Sukamanah (Suka Manah)'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Tanjakan', 'slug' => Str::slug('Tanjakan'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Tanjakan Mekar', 'slug' => Str::slug('Tanjakan Mekar'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Sukasari (Suka Sari)', 'slug' => Str::slug('Sukasari (Suka Sari)'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Ranca Bango', 'slug' => Str::slug('Ranca Bango'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Daon', 'slug' => Str::slug('Daon'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Mekarsari', 'slug' => Str::slug('Mekarsari'), 'district_id' => $district_23->id]);
        SubDistrict::create(['name' => 'Sindangsari (Sindang Sari)', 'slug' => Str::slug('Sindangsari (Sindang Sari)'), 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Kutabumi (Kuta Bumi)', 'slug' => Str::slug('Kutabumi (Kuta Bumi)'), 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Kuta Jaya', 'slug' => Str::slug('Kuta Jaya'), 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Kuta Baru', 'slug' => Str::slug('Kuta Baru'), 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Pasar Kemis', 'slug' => Str::slug('Pasar Kemis'), 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Sukamantri', 'slug' => Str::slug('Sukamantri'), 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Pangadegan', 'slug' => Str::slug('Pangadegan'), 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Gelam Jaya', 'slug' => Str::slug('Gelam Jaya'), 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Suka Asih (Sukaasih)', 'slug' => Str::slug('Suka Asih (Sukaasih)'), 'district_id' => $district_24->id]);
        SubDistrict::create(['name' => 'Teluknaga (Teluk Naga)', 'slug' => Str::slug('Teluknaga (Teluk Naga)'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Bojong Renged', 'slug' => Str::slug('Bojong Renged'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Babakan Asem', 'slug' => Str::slug('Babakan Asem'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Keboncau (Kebon Cau)', 'slug' => Str::slug('Keboncau (Kebon Cau)'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Pangkalan', 'slug' => Str::slug('Pangkalan'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Kampung Melayu Timur', 'slug' => Str::slug('Kampung Melayu Timur'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Kampung Melayu Barat', 'slug' => Str::slug('Kampung Melayu Barat'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Muara', 'slug' => Str::slug('Muara'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Lemo', 'slug' => Str::slug('Lemo'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Tanjung Pasir', 'slug' => Str::slug('Tanjung Pasir'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Tegal Angus', 'slug' => Str::slug('Tegal Angus'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Tanjung Burung', 'slug' => Str::slug('Tanjung Burung'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Kampung Besar', 'slug' => Str::slug('Kampung Besar'), 'district_id' => $district_25->id]);
        SubDistrict::create(['name' => 'Kosambi Barat', 'slug' => Str::slug('Kosambi Barat'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Salembaran Jaya (Salembaran Raya)', 'slug' => Str::slug('Salembaran Jaya (Salembaran Raya)'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Dadap', 'slug' => Str::slug('Dadap'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Kosambi Timur', 'slug' => Str::slug('Kosambi Timur'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Salembaran Jati', 'slug' => Str::slug('Salembaran Jati'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Ranga Rengas (Rawa Rengas)', 'slug' => Str::slug('Ranga Rengas (Rawa Rengas)'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Rawa Burung', 'slug' => Str::slug('Rawa Burung'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Cengklong', 'slug' => Str::slug('Cengklong'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Belimbing', 'slug' => Str::slug('Belimbing'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Jati Mulya (Jatimulya)', 'slug' => Str::slug('Jati Mulya (Jatimulya)'), 'district_id' => $district_26->id]);
        SubDistrict::create(['name' => 'Pakuhaji', 'slug' => Str::slug('Pakuhaji'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Paku Alam', 'slug' => Str::slug('Paku Alam'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Bunisari (Bonasari)', 'slug' => Str::slug('Bunisari (Bonasari)'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Rawa Boni', 'slug' => Str::slug('Rawa Boni'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Buaran Mangga', 'slug' => Str::slug('Buaran Mangga'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Buaran Bambu', 'slug' => Str::slug('Buaran Bambu'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Kalibaru', 'slug' => Str::slug('Kalibaru'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Kohod', 'slug' => Str::slug('Kohod'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Kramat', 'slug' => Str::slug('Kramat'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Sukawali', 'slug' => Str::slug('Sukawali'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Surya Bahari', 'slug' => Str::slug('Surya Bahari'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Kiara Payung', 'slug' => Str::slug('Kiara Payung'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Laksana', 'slug' => Str::slug('Laksana'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Gaga', 'slug' => Str::slug('Gaga'), 'district_id' => $district_27->id]);
        SubDistrict::create(['name' => 'Sepatan', 'slug' => Str::slug('Sepatan'), 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Karet', 'slug' => Str::slug('Karet'), 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Kayu Agung', 'slug' => Str::slug('Kayu Agung'), 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Kayu Bongkok', 'slug' => Str::slug('Kayu Bongkok'), 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Pondok Jaya', 'slug' => Str::slug('Pondok Jaya'), 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Pisangan Jaya', 'slug' => Str::slug('Pisangan Jaya'), 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Mekar Jaya', 'slug' => Str::slug('Mekar Jaya'), 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Sarakan', 'slug' => Str::slug('Sarakan'), 'district_id' => $district_28->id]);
        SubDistrict::create(['name' => 'Curug Kulon', 'slug' => Str::slug('Curug Kulon'), 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Sukabakti (Suka Bakti)', 'slug' => Str::slug('Sukabakti (Suka Bakti)'), 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Binong', 'slug' => Str::slug('Binong'), 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Curug Wetan', 'slug' => Str::slug('Curug Wetan'), 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Kadu', 'slug' => Str::slug('Kadu'), 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Kadu Jaya', 'slug' => Str::slug('Kadu Jaya'), 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Cukanggalih (Cukang Galih)', 'slug' => Str::slug('Cukanggalih (Cukang Galih)'), 'district_id' => $district_29->id]);
        SubDistrict::create(['name' => 'Sukamulya (Suka Mulya)', 'slug' => Str::slug('Sukamulya (Suka Mulya)'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Bunder', 'slug' => Str::slug('Bunder'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Cibadak', 'slug' => Str::slug('Cibadak'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Talaga', 'slug' => Str::slug('Talaga'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Talagasari (Talaga Sari)', 'slug' => Str::slug('Talagasari (Talaga Sari)'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Dukuh', 'slug' => Str::slug('Dukuh'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Cikupa', 'slug' => Str::slug('Cikupa'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Sukanagara (Suka Nagara)', 'slug' => Str::slug('Sukanagara (Suka Nagara)'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Bitung Jaya', 'slug' => Str::slug('Bitung Jaya'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Pasir Gadung', 'slug' => Str::slug('Pasir Gadung'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Sukadamai (Suka Damai)', 'slug' => Str::slug('Sukadamai (Suka Damai)'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Pasir Jaya', 'slug' => Str::slug('Pasir Jaya'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Budi Mulya', 'slug' => Str::slug('Budi Mulya'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Bojong', 'slug' => Str::slug('Bojong'), 'district_id' => $district_30->id]);
        SubDistrict::create(['name' => 'Mekar Bakti', 'slug' => Str::slug('Mekar Bakti'), 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Ranca Iyuh', 'slug' => Str::slug('Ranca Iyuh'), 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Peusar', 'slug' => Str::slug('Peusar'), 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Ranca Kalapa', 'slug' => Str::slug('Ranca Kalapa'), 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Serdang Kulon', 'slug' => Str::slug('Serdang Kulon'), 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Mekar Jaya', 'slug' => Str::slug('Mekar Jaya'), 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Ciakar', 'slug' => Str::slug('Ciakar'), 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Panongan', 'slug' => Str::slug('Panongan'), 'district_id' => $district_31->id]);
        SubDistrict::create(['name' => 'Babakan', 'slug' => Str::slug('Babakan'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Caringin', 'slug' => Str::slug('Caringin'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Serdang Wetan', 'slug' => Str::slug('Serdang Wetan'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Babat', 'slug' => Str::slug('Babat'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Ciangir', 'slug' => Str::slug('Ciangir'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Legok', 'slug' => Str::slug('Legok'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Palasari (Pala Sari)', 'slug' => Str::slug('Palasari (Pala Sari)'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Bojongkamal (Bojong Kamal)', 'slug' => Str::slug('Bojongkamal (Bojong Kamal)'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Rancagong', 'slug' => Str::slug('Rancagong'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Kamuning (Kemuning)', 'slug' => Str::slug('Kamuning (Kemuning)'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Cirarab', 'slug' => Str::slug('Cirarab'), 'district_id' => $district_32->id]);
        SubDistrict::create(['name' => 'Medang', 'slug' => Str::slug('Medang'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Cicalengka', 'slug' => Str::slug('Cicalengka'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Pagedangan', 'slug' => Str::slug('Pagedangan'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Cijantra', 'slug' => Str::slug('Cijantra'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Lengkong Kulon', 'slug' => Str::slug('Lengkong Kulon'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Situ Gadung', 'slug' => Str::slug('Situ Gadung'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Jatake', 'slug' => Str::slug('Jatake'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Cihuni', 'slug' => Str::slug('Cihuni'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Kadu Sirung', 'slug' => Str::slug('Kadu Sirung'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Malang Nengah', 'slug' => Str::slug('Malang Nengah'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Karang Tengah', 'slug' => Str::slug('Karang Tengah'), 'district_id' => $district_33->id]);
        SubDistrict::create(['name' => 'Cisauk', 'slug' => Str::slug('Cisauk'), 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Mekar Wangi (Mekarwangi)', 'slug' => Str::slug('Mekar Wangi (Mekarwangi)'), 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Suradita', 'slug' => Str::slug('Suradita'), 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Sampora', 'slug' => Str::slug('Sampora'), 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Dangdang', 'slug' => Str::slug('Dangdang'), 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Cibogo', 'slug' => Str::slug('Cibogo'), 'district_id' => $district_34->id]);
        SubDistrict::create(['name' => 'Benda', 'slug' => Str::slug('Benda'), 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Sukamulya (Suka Mulya)', 'slug' => Str::slug('Sukamulya (Suka Mulya)'), 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Kaliasin (Kali Asin)', 'slug' => Str::slug('Kaliasin (Kali Asin)'), 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Buniayu (Buni Ayu)', 'slug' => Str::slug('Buniayu (Buni Ayu)'), 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Parahu', 'slug' => Str::slug('Parahu'), 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Merak', 'slug' => Str::slug('Merak'), 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Bunar', 'slug' => Str::slug('Bunar'), 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Kubang', 'slug' => Str::slug('Kubang'), 'district_id' => $district_35->id]);
        SubDistrict::create(['name' => 'Kelapa Dua', 'slug' => Str::slug('Kelapa Dua'), 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Bencongan', 'slug' => Str::slug('Bencongan'), 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Bencongan Indah', 'slug' => Str::slug('Bencongan Indah'), 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Pakulonan Barat', 'slug' => Str::slug('Pakulonan Barat'), 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Bojong Nangka', 'slug' => Str::slug('Bojong Nangka'), 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Curug Sangerang (Curug Sangereng)', 'slug' => Str::slug('Curug Sangerang (Curug Sangereng)'), 'district_id' => $district_36->id]);
        SubDistrict::create(['name' => 'Sindang Jaya', 'slug' => Str::slug('Sindang Jaya'), 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Wanakerta (Wana Kerta)', 'slug' => Str::slug('Wanakerta (Wana Kerta)'), 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Sukaharja (Suka Harja)', 'slug' => Str::slug('Sukaharja (Suka Harja)'), 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Sindangasih (Sindang Asih)', 'slug' => Str::slug('Sindangasih (Sindang Asih)'), 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Sindangpanon (Sindang Panon)', 'slug' => Str::slug('Sindangpanon (Sindang Panon)'), 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Sindangsono (Sindang Sono)', 'slug' => Str::slug('Sindangsono (Sindang Sono)'), 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Badak Anom', 'slug' => Str::slug('Badak Anom'), 'district_id' => $district_37->id]);
        SubDistrict::create(['name' => 'Kedaung Barat', 'slug' => Str::slug('Kedaung Barat'), 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Lebak Wangi', 'slug' => Str::slug('Lebak Wangi'), 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Jati Mulya', 'slug' => Str::slug('Jati Mulya'), 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Sangiang', 'slug' => Str::slug('Sangiang'), 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Gempol Sari', 'slug' => Str::slug('Gempol Sari'), 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Kampung Kelor', 'slug' => Str::slug('Kampung Kelor'), 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Pondok Kelor', 'slug' => Str::slug('Pondok Kelor'), 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Tanah Merah', 'slug' => Str::slug('Tanah Merah'), 'district_id' => $district_38->id]);
        SubDistrict::create(['name' => 'Solear', 'slug' => Str::slug('Solear'), 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Cikuya', 'slug' => Str::slug('Cikuya'), 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Cikasungka', 'slug' => Str::slug('Cikasungka'), 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Cireundeu', 'slug' => Str::slug('Cireundeu'), 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Cikareo', 'slug' => Str::slug('Cikareo'), 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Pasanggrahan', 'slug' => Str::slug('Pasanggrahan'), 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Munjul', 'slug' => Str::slug('Munjul'), 'district_id' => $district_39->id]);
        SubDistrict::create(['name' => 'Gunung Kaler', 'slug' => Str::slug('Gunung Kaler'), 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Sidoko', 'slug' => Str::slug('Sidoko'), 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Rancagede (Ranca Gede)', 'slug' => Str::slug('Rancagede (Ranca Gede)'), 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Kedung', 'slug' => Str::slug('Kedung'), 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Cipaeh', 'slug' => Str::slug('Cipaeh'), 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Onyam', 'slug' => Str::slug('Onyam'), 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Tamiang', 'slug' => Str::slug('Tamiang'), 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Kandawati (Kanda Wati)', 'slug' => Str::slug('Kandawati (Kanda Wati)'), 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Cibetok', 'slug' => Str::slug('Cibetok'), 'district_id' => $district_40->id]);
        SubDistrict::create(['name' => 'Mekar Baru', 'slug' => Str::slug('Mekar Baru'), 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Kedaung', 'slug' => Str::slug('Kedaung'), 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Cijeruk', 'slug' => Str::slug('Cijeruk'), 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Waliwis', 'slug' => Str::slug('Waliwis'), 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Klutuk', 'slug' => Str::slug('Klutuk'), 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Jenggot', 'slug' => Str::slug('Jenggot'), 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Kosambi Dalam', 'slug' => Str::slug('Kosambi Dalam'), 'district_id' => $district_41->id]);
        SubDistrict::create(['name' => 'Gandaria (Ganda Ria)', 'slug' => Str::slug('Gandaria (Ganda Ria)'), 'district_id' => $district_41->id]);
    }
}
